import Head from "next/head"
import { Nav } from "./Nav"
import { Flex } from "@chakra-ui/react"
import { useBackgroundColor } from "@evy/styling"

type Props = {
  children: React.ReactNode

  title?: string
}

const Layout = ({ children, title }: Props) => {
  const bg = useBackgroundColor()
  return <>
    <Head>
      <title>📚 Evy {title !== undefined ? `| ${title}` : ''}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav />
    <Flex
      minH='100vh'
      justify='center'
      bg={bg}
    >
      {children}
    </Flex>
  </>
}

export default Layout